-- Clear all data from tables
TRUNCATE TABLE marks CASCADE;
TRUNCATE TABLE exams CASCADE;
TRUNCATE TABLE exam_periods CASCADE;
TRUNCATE TABLE exam_templates CASCADE;
TRUNCATE TABLE attendance CASCADE;
TRUNCATE TABLE students CASCADE;
TRUNCATE TABLE subjects CASCADE;
TRUNCATE TABLE classes CASCADE;
TRUNCATE TABLE requests CASCADE;
TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE schools CASCADE;
